### ISSUE TITLE
Remove optima dependency?

### ISSUE THREAD

**Issue by snunez1** [alex-gutev/cl-environments#14]
Is it possible to remove the optima dependency?  There seems to be [only one pattern](https://github.com/alex-gutev/cl-environments/blob/e6cd3b5e1cabd27e1162d1c33d2d8c841e5158d4/src/walker/util.lisp#L72).  The reason is licensing; although cl-environments is MIT licensed, the transitive dependency, optima, has a restrictive license, meaning cl-environments can't be used where such licenses are not allowed.

Happy to help strip it out if this is something can be done without a huge amount of effort.

**Comment by alex-gutev** [comment]
I'm no export on these matters but as far as I know its licensed under LLPGL (which itself is a special case of the LGPL for Lisp) which means which is not transitive like the GPL unless the core of the library (optima) is modified, which it is not in this case.

Anyway I believe optima should be replaced since it's been archived and will not be maintained anymore. trivia seems to b the way to go.

I will get to it but you're welcome to help out if you like. Just a few things to keep in mind if you do:

1. The library has implementation-specific code for SBCL, CCL, LispWorks, and Allegro with a common code for the remaing implementations.
2. This library is a core dependency of [cl-form-types](https://github.com/alex-gutev/cl-form-types), [static-dispatch](https://github.com/alex-gutev/static-dispatch), and [generic-cl](https://github.com/alex-gutev/generic-cl) so make sure the tests of those libraries pass as well as cl-environments.

Edit: The replacement trivia is also under the same license LLGPL.

**Comment by snunez1** [comment]
Most corporations operate on a white-list principle, explicitly permitting a handful of licenses.  Exceptions can be applied for, but rarely granted because trying to get a corporate lawyer to review a license just to get a common lisp library approved is a battle a project manager is not willing to fight, especially since there's so many permissive licenses out there.

Perhaps we need a 'just enough' library for pattern matching that's MIT licensed?  Personally I use [let+](https://github.com/sharplispers/let-plus) for a lot of these use cases, and there are [other options](https://www.cliki.net/pattern%20matching).  Screamer looks interesting.

**Comment by alex-gutev** [comment]
Pattern matching is not strictly required, every pattern can be implemented using `(if ...)` however pattern matching makes the code much cleaner and easier to understand, especially when code walking and parsing declarations. I think let+ can only cover those cases where pattern matching is used for destructuring but not destructuring + branching. I think screamer may be overkill, it's more of an implementation of Prolog for Lisp. If there is a drop-in replacement for optima that is MIT/BSD licensed or the pattern matching can be unrolled to a combination if `if` + `let+` without compromising on readability too much, then I will consider it.
