### ISSUE TITLE
`cl-environments-cl` does not make `lambda` work in accordance with CLTL2

### ISSUE THREAD

**Issue by digikar99** [alex-gutev/cl-environments#8]
For instance, on CCL:

```lisp
(in-package :cl-user)

(defmacro var-type (var &environment env)
  (print (multiple-value-list (cl-environments-cl:variable-information var env)))
  var)

(cl-environments:define-declaration my-decl (vars)  
  (values :variable
          (mapcar (lambda (x) (list x 'my-decl t)) vars)))

(defun foo (x)
  (declare (my-decl x))
  (var-type x))
; prints: (:LEXICAL T NIL)

(cl-environments-cl:defun foo (x)
  (declare (my-decl x))
  (var-type x))
; prints as expected: (:LEXICAL T ((MY-DECL . T)))

(cl-environments-cl:lambda (x)
  (declare (my-decl x))
  (var-type x))
; prints against expectation: (:LEXICAL T NIL)
```

This does seem to require shadowing `lambda`, however, doing so also requires shadowing other forms such as `define-condition` (through `:report`) or even `compile` that take lambda expressions.

(EDIT) Perhaps simpler although not the cleanest might be the introduction of a `cltl2-lambda`.

**Comment by alex-gutev** [comment]
I know this issue is more than a year old, but I only got time to look at these issues now.

The reason why `LAMBDA` isn't shadowed is because `CL:LAMBDA` has special semantics in Common Lisp which cannot be replaced with a macro like other forms. For example `LAMBDA` can appear inside `CL:FUNCTION`, `#'...`, forms:

````lisp
#'(cl:lambda (a b) ...)
````

This cannot be replace with a macro which expands to `CL:LAMBDA` since `CL:FUNCTION` does not macroexpand its arguments.

Similarly `CL:LAMBDA` can also appear in the place of a function name in function calls. Example:

````lisp
((cl:lambda (a b) (+ a b) 1 2)
````

This definitely cannot be replaced with a macro, since Common Lisp does not evaluate or macroexpand the function name (it's a Lisp-2 after all). In a function call expression, the function can only be a symbol naming a function or a `CL:LAMBDA` expression.

Something like the following (assuming `cl-environments-cl:lambda` is not just a reexport of `cl:lambda`), will not work:

````lisp
((cl-environments-cl:lambda (a b) (+ a b) 1 2)
````

This solution to this issue is to put the `LAMBDA` form in a form which is shadowed by `cl-environments-cl` and hence walked by the code walker. Alternatively if you really need environment information in a top-level `LAMBDA`, wrap the `LAMBDA`  in `CL-ENVIRONMENTS-CL:WALK-ENVIRONMENT`, more information here https://github.com/alex-gutev/cl-environments#ensuring-code-walking and https://github.com/alex-gutev/cl-environments#walk-environment.

**Comment by alex-gutev** [comment]
There's not much that can be done to solve this issue at the moment. The only option is to introduce a `cltl2-lambda` macro or to replace the standard Common Lisp reader and perform code-walking at that point, which is isn't worth it in my opinion. If you'd like to a `cltl2-lambda` macro, open a new issue with a feature request.

**Comment by digikar99** [comment]
Yes, I agree, this is best left as it is. 
Replacing `lambda` needs to be done explicitly, ensuring that no `custom-lambda` is emitted in the final expansion. 
For the moment, cl-environments is good the way it is.
